### ISSUE TITLE
Google V8 Engine is not supported to build on Visual Studio 2017

### ISSUE THREAD

**Issue by ghost** [goldsborough/latexpp#3]
Hi.
I tried to use your latexpp library so I tried to build Google V8 Engine.
But Google V8 Engine is not supported Visual Studio 2017.
Do I install Visual Studio 2015 and build Google V8 Engine?
Thanks to read my question.

**Comment by ghost** [comment]
This is the error of building Google V8 Engine.

Cannot rebase: You have unstaged changes.
Please commit or stash them.
Failed to update depot_tools.

________ running 'D:\Tools\depot_tools\python276_bin\python.exe v8/gypfiles/landmines.py' in 'D:\Library'
Traceback (most recent call last):
  File "v8/gypfiles/landmines.py", line 245, in <module>
    sys.exit(main())
  File "v8/gypfiles/landmines.py", line 232, in main
    gyp_environment.set_environment()
  File "D:\Library\v8\gypfiles\gyp_environment.py", line 60, in set_environment
    vs_toolchain.SetEnvironmentAndGetRuntimeDllDirs()
  File "D:\Library\v8\gypfiles\vs_toolchain.py", line 76, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "D:\Library\v8\gypfiles\vs_toolchain.py", line 130, in DetectVisualStudioPath
    version_as_year, ', '.join(year_to_version.keys())))
Exception: Visual Studio version 2017 (from GYP_MSVS_VERSION) not supported. Supported versions are: 2015, 2013
Error: Command 'D:\\Tools\\depot_tools\\python276_bin\\python.exe v8/gypfiles/landmines.py' returned non-zero exit status 1 in D:\Library

Thanks.
